# query getLibrarySongs {
# 	getLibrary {
# 		songs {
# 			mix
# 			title
# 			songID
# 			duration
# 			inLibrary
# 			dateAddedToLibrary
# 			featuring {
# 				artistID
# 				name
# 			}
# 			remixers {
# 				artistID
# 				name
# 			}
# 			artists {
# 				artistID
# 				name
# 			}
# 			genres {
# 				genreID
# 				name
# 			}
# 			album {
# 				title
# 				albumID
# 				artists {
# 					artistID
# 					name
# 				}
# 			}
# 			userPlays {
# 				playID
# 				dateCreated
# 			}
# 		}
# 		albums {
# 			title
# 			albumID
# 			released
# 			artists {
# 				artistID
# 				name
# 			}
# 		}
# 		artists {
# 			name
# 			artistID
# 			inLibrary
# 			albumsTotal
# 			dateAddedToLibrary
# 		}
# 		genres {
# 			name
# 			genreID
# 		}
# 		playlists {
# 			title
# 			inLibrary
# 			playlistID
# 			songsTotal
# 			dateAddedToLibrary
# 			user {
# 				name
# 				userID
# 			}
# 		}
# 	}
# }