query getSongPage($songID: UUID!) {
  getSongByID(songID: $songID) {
    mix
    bpm
    size
    title
    songID
    duration
    inLibrary
    playsTotal
    userPlaysTotal
    key {
      flat
      keyID
      sharp
      camelot
    }
    featuring {
      name
      artistID
    }
    remixers {
      name
      artistID
    }
    artists {
      name
      artistID
    }
    genres {
      name
      genreID
    }
    album {
      title
      albumID
      released
    }
  }
}
