query getTopOneHundredSongs {
	topOneHundredSongs {
		mix
		title
		songID
		playsTotal
		featuring {
			artistID
			name
		}
		remixers {
			artistID
			name
		}
		artists {
			artistID
			name
		}
		genres {
			genreID
			name
		}
		album {
			title
			albumID
			released
		}
	}
}