#import "../../graphql/fragments/song-core.gql";

mutation addSongToPlaylist($songID: UUID!, $playlistID: UUID!) {
	addSongToPlaylist(songID: $songID, playlistID: $playlistID) {
		playlistID
		songsTotal
		songs {
			...SongCoreFragment
			playlistIndex(playlistID: $playlistID)
		}
	}
}
