#import "../../graphql/fragments/playlist-core.gql";

query getUserPlaylistsFilteredBySong($songID: UUID!) {
	getUser {
		userID
		playlistsFilteredBySong(songID: $songID) {
			...PlaylistCoreFragment
		}
	}
}
