#import "../../graphql/fragments/song-core.gql";
#import "../../graphql/fragments/album-core.gql";

query getAlbumPage($albumID: UUID!) {
	getAlbumByID(albumID: $albumID) {
		...AlbumCoreFragment
		duration
		songsTotal
		genres {
			genreID
			name
		}
		songs {
			...SongCoreFragment
			playsTotal
			discNumber
			trackNumber
		}
	}
}