mutation AddAlbumToPlaylist(
	$albumID: UUID!
	$playlistID: UUID!
) {
	addAlbumToPlaylist(
		albumID: $albumID
		playlistID: $playlistID
	) {
		playlistID
		songs {
			mix
			title
			songID
			duration
			inLibrary
			playsTotal
			discNumber
			trackNumber
			playlistIndex(playlistID: $playlistID)
			featuring {
				name
				artistID
			}
			remixers {
				name
				artistID
			}
			artists {
				name
				artistID
			}
			genres {
				name
				genreID
			}
			album {
				title
				albumID
			}
		}
	}
}