#import "../../graphql/fragments/song-core.gql";
#import "../../graphql/fragments/album-core.gql";
#import "../../graphql/fragments/playlist-core.gql";

query getBrowsePage {
	getTopTenSongs {
		...SongCoreFragment
		playsTotal
	}
	getTrendingAlbums {
    ...AlbumCoreFragment
	}
	getTrendingPlaylists {
		...PlaylistCoreFragment
	}
}