mutation playSong($songID: UUID!) {
  playSong(songID: $songID) {
    userID
    nowPlaying {
      mix
      title
      songID
      duration
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
  }
}
