#import "../../graphql/fragments/song-core.gql";
#import "../../graphql/fragments/playlist-core.gql";

query getPlaylistPage($playlistID: UUID!) {
	getPlaylistByID(playlistID: $playlistID) {
		...PlaylistCoreFragment
		privacy
		duration
		dateCreated
		songs {
			...SongCoreFragment
			playlistIndex(playlistID: $playlistID)
		}
	}
}
