mutation removeSongFromPlaylist($playlistID: UUID!, $index: NonNegativeInt!) {
	removeSongFromPlaylist(index: $index, playlistID: $playlistID) {
		playlistID
		songsTotal
		songs {
			songID
		}
	}
}
