mutation clearNextQueues {
	clearNextQueues {
    userID
    queuePrevious {
      mix
      title
      songID
      duration
			inLibrary
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
    nowPlaying {
      mix
      title
      songID
      duration
			inLibrary
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
    queueNext {
      mix
      title
      songID
      duration
			inLibrary
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
    queueLater {
      mix
      title
      songID
      duration
			inLibrary
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
  }
}