query getQueueNext {
  getQueue {
    next {
      mix
      title
      songID
      duration
      inLibrary
      queueIndex
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
  }
}