query getQueuePrevious {
  user {
    userID
    queuePrevious {
      mix
      title
      songID
      duration
      queueIndex
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
  }
}
