#import "../../graphql/fragments/song-core.gql";

query getArtistPageSongs(
	$artistID: UUID!
	$songsOrderBy: SongsOrderByInput!
) {
	getArtistByID(artistID: $artistID) {
		artistID
		songs(orderBy: $songsOrderBy) {
			...SongCoreFragment
		}
	}
}