#import "../../graphql/fragments/song-core.gql";

query getArtistPageHome($artistID: UUID!) {
	getArtistByID(artistID: $artistID) {
		artistID
		topTenSongs {
			...SongCoreFragment
			playsTotal
		}
	}
}
