#import "../../graphql/fragments/album-core.gql";

query getArtistPageAlbums($artistID: UUID!, $orderBy: AlbumsOrderByInput!) {
	getArtistByID(artistID: $artistID) {
		artistID
		albums(orderBy: $orderBy) {
			...AlbumCoreFragment
			playsTotal
		}
	}
}
