mutation nextQueueSong {
	nextQueueSong {
		userID
    queuePrevious {
      mix
      title
      songID
      duration
      queueIndex
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
		nowPlaying {
			mix
			title
			songID
			duration
			featuring {
				artistID
				name
			}
			remixers {
				artistID
				name
			}
			artists {
				artistID
				name
			}
			genres {
				genreID
				name
			}
			album {
				albumID
				title
			}
		}
    queueNext {
      mix
      title
      songID
      duration
      queueIndex
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
    queueLater {
      mix
      title
      songID
      duration
      queueIndex
      featuring {
        artistID
        name
      }
      remixers {
        artistID
        name
      }
      artists {
        artistID
        name
      }
      genres {
        genreID
        name
      }
      album {
        albumID
        title
      }
    }
	}
}
