type Album {
	# base
	albumID: UUID!
	released: Date!
	title: NonEmptyString!
	duration: PositiveInt!

	# relationships
	songs: [Song!]!
	genres: [Genre!]!
	artists: [Artist!]!
	playsTotal: PositiveInt
	songsTotal: PositiveInt!

	# user
	userPlays: [Play!]
	userPlaysTotal: PositiveInt

	# library
	inLibrary: Boolean!
}