input LogInInput {
	password: NonEmptyString!
	emailAddress: EmailAddress!
}

input SignUpInput {
	cover: Upload!
	profile: Upload!
	name: NonEmptyString!
	password: NonEmptyString!
	emailAddress: EmailAddress!
}

input CreatePlaylistInput {
	title: NonEmptyString!
	privacy: PlaylistPrivacy!
}

input UpdatePlaylistTitleInput {
	playlistID: UUID!
	title: NonEmptyString!
}

input ShuffleLibraryCustomInput {
	genres: [UUID!]
	artists: [UUID!]
}

input UpdatePlaylistPrivacyInput {
	playlistID: UUID!
	privacy: PlaylistPrivacy!
}

input GetSearchResultsInput {
	value: NonEmptyString!
	length: NonNegativeInt!
}

input SongsOrderByInput {
	field: SongsOrderByField!
	direction: OrderByDirection!
}

input AlbumsOrderByInput {
	field: AlbumsOrderByField!
	direction: OrderByDirection!
}

input GenresOrderByInput {
	field: GenresOrderByField!
	direction: OrderByDirection!
}

input LibrarySongsOrderByInput {
	direction: OrderByDirection!
	field: LibrarySongsOrderByField!
}

input LibraryArtistsOrderByInput {
	direction: OrderByDirection!
	field: LibraryArtistsOrderByField!
}

input LibraryPlaylistsOrderByInput {
	direction: OrderByDirection!
	field: LibraryPlaylistsOrderByField!
}

input LibraryAlbumsInput {
	page: NonNegativeInt!
	orderBy: AlbumsOrderByInput
}

input LibraryGenresInput {
	page: NonNegativeInt!
	orderBy: GenresOrderByInput
}

input LibrarySongsInput {
	page: NonNegativeInt!
	orderBy: LibrarySongsOrderByInput
}

input LibraryArtistsInput {
	page: NonNegativeInt!
	orderBy: LibraryArtistsOrderByInput
}

input LibraryPlaylistsInput {
	page: NonNegativeInt!
	orderBy: LibraryPlaylistsOrderByInput
}