type Playlist {
	# base
	playlistID: UUID!
	duration: PositiveInt
	title: NonEmptyString!
	dateCreated: Timestamp!
	privacy: PlaylistPrivacy!
	
	# relationships
	user: User!
	songs: [Song!]
	playsTotal: PositiveInt
	songsTotal: PositiveInt

	# user
	userPlays: [Play!]
	userPlaysTotal: PositiveInt

	# library
	inLibrary: Boolean!
	dateAddedToLibrary: Timestamp
}