type User {
	userID: UUID!
	plays: [Play!]
	followers: [User!]
	isFollower: Boolean!
	isFollowing: Boolean!
	name: NonEmptyString!
	playlists: [Playlist!]
	dateJoined: Timestamp!
	playsTotal: PositiveInt
	playlistsTotal: PositiveInt
	playlistsFilteredBySong(songID: UUID!): [Playlist!]
	playlistsFilteredByAlbum(albumID: UUID!): [Playlist!]
}