type User {
	userID: UUID!
	plays: [Play!]
	email: EmailAddress!
	name: NonEmptyString!
	playlists: [Playlist!]
	dateJoined: Timestamp!
	playsTotal: PositiveInt
	phoneNumber: PhoneNumber!
	playlistsTotal: PositiveInt
	playlistsFilteredBySong(songID: UUID!): [Playlist!]!
	playlistsFilteredByAlbum(albumID: UUID!): [Playlist!]!
}