query getArtistPageHome($artistID: UUID!) {
	getArtistByID(artistID: $artistID) {
		artistID
		topTenSongs {
			songID
			mix
			title
			duration
			inLibrary
			playsTotal
			featuring {
				artistID
				name
			}
			remixers {
				artistID
				name
			}
			artists {
				artistID
				name
			}
			genres {
				genreID
				name
			}
			album {
				albumID
				title
			}
		}
	}
}