query getArtistPageAlbums(
	$artistID: UUID!
	$orderBy: AlbumsOrderByInput!
) {
	getArtistByID(artistID: $artistID) {
		artistID
		albums(orderBy: $orderBy) {
			title
			albumID
			released
			inLibrary
			artists {
				artistID
				name
			}
		}
	}
}