#import "../../../graphql/fragments/queue-next.gql";
#import "../../../graphql/fragments/queue-later.gql";

mutation removeSongFromQueueNext($index: NonNegativeInt!) {
	removeSongFromQueueNext(index: $index) {
		...QueueNextFragment
		...QueueLaterFragment
	}
}
