type Artist {
	# base
	artistID: UUID!
	city: NonEmptyString
	name: NonEmptyString!
	country: NonEmptyString

	# library
	inLibrary: Boolean!
	dateAddedToLibrary: TimeStamp

	# user
	userPlaysTotal: PositiveInt

	# relationships
	since: TimeStamp!
	topTenSongs: [Song!]!
	playsTotal: PositiveInt
	songsTotal: PositiveInt!
	albumsTotal: PositiveInt!
	songs(orderBy: SongsOrderByInput!): [Song!]!
	albums(orderBy: AlbumsOrderByInput!): [Album!]!
}
