type Genre {
	# base
	genreID: UUID!
	name: NonEmptyString!

	# user
	userPlaysTotal: PositiveInt

	# relationships
	songsTotal: PositiveInt
	playsTotal: PositiveInt
	songs(orderBy: SongsOrderByInput!): [Song!]!
}
