type Library {
	duration: PositiveInt
	songsTotal: NonNegativeInt
	albumsTotal: NonNegativeInt
	genresTotal: NonNegativeInt
	artistsTotal: NonNegativeInt
	playlistsTotal: NonNegativeInt
	songAtIndex(input: LibrarySongAtIndexInput!): Song
	genreAtIndex(input: LibraryGenreAtIndexInput!): Genre
	albumAtIndex(input: LibraryAlbumAtIndexInput!): Album
	artistAtIndex(input: LibraryArtistAtIndexInput!): Artist
	playlistAtIndex(input: LibraryPlaylistAtIndexInput!): Playlist
}
