type Playlist {
	# base
	playlistID: UUID!
	duration: PositiveInt
	title: NonEmptyString!
	dateCreated: TimeStamp!
	privacy: PlaylistPrivacy!

	# relationships
	user: User!
	songs: [Song!]
	playsTotal: PositiveInt
	songsTotal: PositiveInt

	# user
	userPlaysTotal: PositiveInt

	# library
	inLibrary: Boolean!
	dateAddedToLibrary: TimeStamp
}
