type Query {
	getUser: User!
	getQueue: Queue!
	getLibrary: Library!
	getTopTenSongs: [Song!]!
	getTrendingSongs: [Song!]!
	getTrendingAlbums: [Album!]!
	getPlaysTotal: NonNegativeInt!
	getTrendingArtists: [Artist!]!
	getTopOneHundredSongs: [Song!]!
	getUserByID(userID: UUID!): User!
	getPlayByID(playID: UUID!): Play!
	getSongByID(songID: UUID!): Song!
	getTrendingPlaylists: [Playlist!]!
	getAlbumByID(albumID: UUID!): Album!
	getGenreByID(genreID: UUID!): Genre!
	getArtistByID(artistID: UUID!): Artist!
	getPlaylistByID(playlistID: UUID!): Playlist!
}
