type Song {
	# base
	mix: String!
	songID: UUID!
	bpm: PositiveInt!
	size: PositiveInt!
	title: NonEmptyString!
	duration: PositiveInt!
	discNumber: PositiveInt!
	trackNumber: PositiveInt!

	# relationships
	key: Key!
	album: Album!
	genres: [Genre!]!
	artists: [Artist!]!
	remixers: [Artist!]!
	featuring: [Artist!]!
	playsTotal: PositiveInt

	# user
	userPlaysTotal: PositiveInt

	# library
	inLibrary: Boolean!
	dateAddedToLibrary: TimeStamp

	# queue
	queueIndex: NonNegativeInt

	# other
	isInPlaylist(playlistID: UUID!): Boolean!
	playlistIndex(playlistID: UUID!): NonNegativeInt
	dateAddedToPlaylist(playlistID: UUID!): TimeStamp
}
