type User {
	userID: UUID!
	followers: [User!]
	isFollower: Boolean!
	name: NonEmptyString!
	isFollowing: Boolean!
	dateJoined: TimeStamp!
	playlists: [Playlist!]
	playsTotal: PositiveInt
	emailAddress: EmailAddress!
	playlistsTotal: PositiveInt
	playlistsFilteredBySong(songID: UUID!): [Playlist!]
}
