query getUserPlaylistsFilteredBySong($songID: UUID!) {
	getUser {
		userID
		playlistsFilteredBySong(songID: $songID) {
			title
			playlistID
			songsTotal
			user {
				name
				userID
			}
		}
	}
}