query getPlaylistPage($playlistID: UUID!) {
	getPlaylistByID(playlistID: $playlistID) {
		title
		isPublic
		inLibrary
		songsTotal
		playlistID
		dateCreated
		user {
			name
			userID
		}
		songs {
			mix
			title
			songID
			duration
			inLibrary
			playsTotal
			discNumber
			trackNumber
			playlistIndex(playlistID: $playlistID)
			featuring {
				name
				artistID
			}
			remixers {
				name
				artistID
			}
			artists {
				name
				artistID
			}
			genres {
				name
				genreID
			}
			album {
				title
				albumID
			}
		}
	}
}