query getUserPlaylistsFilteredByAlbum($albumID: UUID!) {
	getUser {
		userID
		playlistsFilteredByAlbum(albumID: $albumID) {
			title
			playlistID
			songsTotal
			user {
				name
				userID
			}
		}
	}
}