fragment UserQueuesFragment on User {
	userID
	queuePrevious {
		songID
		queueIndex
	}
	nowPlaying {
		songID
		queueIndex
	}
	queueNext {
		songID
		queueIndex
	}
	queueLater {
		songID
		queueIndex
	}
}