query getAlbumPage($albumID: UUID!) {
	getAlbumByID(albumID: $albumID) {
		albumID
		title
		released
		inLibrary
		genres {
			name
			genreID
		}
		artists {
			name
			artistID
		}
		remixers {
			name
			artistID
		}
		songs {
			mix
			title
			songID
			duration
			inLibrary
			playsTotal
			discNumber
			trackNumber
			featuring {
				artistID
				name
			}
			remixers {
				artistID
				name
			}
			artists {
				artistID
				name
			}
			genres {
				genreID
				name
			}
			album {
				albumID
				title
			}
		}
	}
}