#import "../../../graphql/fragments/song-core.gql";

query writeQueue {
	getQueue {
		previous {
			...SongCoreFragment
		}
		nowPlaying {
			...SongCoreFragment
		}
		next {
			...SongCoreFragment
		}
		later {
			...SongCoreFragment
		}
	}
}
